# Generated by Django 4.2.2 on 2023-06-28 17:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('classroom_year', models.IntegerField(blank=True, help_text='Year in the current stage', null=True, verbose_name='classroom_year')),
                ('classroom_line', models.CharField(blank=True, help_text='Line in the current year', max_length=1, null=True, verbose_name='classroom_line')),
                ('stage', models.CharField(blank=True, choices=[('Infant', 'Infant'), ('Primary', 'Primary'), ('Secondary', 'Secondary')], help_text='Stage of the classroom', max_length=20, null=True, verbose_name='Stage')),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'unique_together': {('classroom_year', 'classroom_line', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, help_text='Name of the student', max_length=50, null=True, verbose_name='Name')),
                ('surname', models.CharField(blank=True, help_text='Surname of the student', max_length=50, null=True, verbose_name='Surname')),
                ('allergies', models.CharField(blank=True, help_text='Allergies of the student', max_length=50, null=True, verbose_name='Allergies')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch_organizer.classroom')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'unique_together': {('name', 'surname')},
            },
        ),
    ]
