# Generated by Django 4.2.2 on 2023-07-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='scholar_year',
            field=models.CharField(blank=True, help_text='Year of the current course', max_length=50, null=True, verbose_name='scholar_year'),
        ),
    ]
