# Generated by Django 4.2.2 on 2023-06-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_organizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
