# Generated by Django 4.2.2 on 2023-06-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_organizer', '0002_rename_students_student'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('classroom_year', 'classroom_line')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('name', 'surname')},
        ),
    ]
