# Generated by Django 4.2.2 on 2023-06-28 17:05

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workcalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField(blank=True, help_text='Date in the year', null=True, verbose_name='Date')),
                ('holiday', models.BooleanField(blank=True, default=False, help_text='True if it is holiday, False if it is not holiday', null=True, verbose_name='Holiday')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
